config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  scope controller: :static_pages do
    get '/help' => :help
    get '/about' => :about
    get '/contact' => redirect("https://github.com/alexsmartens")
  end

  get '/signup', :to => 'users#new'

  scope controller: :sessions do
    get '/login' => :new
    post '/login' => :create
    delete '/logout' => :destroy
  end

  # "resources :resource" - automatically generate a full suite of RESTful routes
  resources :users do
    # "member" method adds additional routes to respond to URLs containing
    # the user id, eg. "/users/id/following" and "/users/id/followers"
    member do
      get :following, :followers
    end
    # "collection" method adds additional routes to respond to URLs without the
    # id, eg. "/users/tigers" as in the method below
    #     collection do
    #       get :tigers
    #     end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reactions

  # Custom handling of common errors
   match "/404", to: "errors#not_found", via: :all
   match "/500", to: "errors#internal_server_error", via: :all
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_reaction, only: %i[ show edit update destroy ]

  # GET /reactions or /reactions.json
  def index
    @reactions = Reaction.all
  end

  # GET /reactions/1 or /reactions/1.json
  def show
  end

  # GET /reactions/new
  def new
    @reaction = Reaction.new
  end

  # GET /reactions/1/edit
  def edit
  end

  # POST /reactions or /reactions.json
  def create
    @reaction = Reaction.new(reaction_params)

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to reaction_url(@reaction), notice: "Reaction was successfully created." }
        format.json { render :show, status: :created, location: @reaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reactions/1 or /reactions/1.json
  def update
    respond_to do |format|
      if @reaction.update(reaction_params)
        format.html { redirect_to reaction_url(@reaction), notice: "Reaction was successfully updated." }
        format.json { render :show, status: :ok, location: @reaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reactions/1 or /reactions/1.json
  def destroy
    @reaction.destroy

    respond_to do |format|
      format.html { redirect_to reactions_url, notice: "Reaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reaction
      @reaction = Reaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reaction_params
      params.fetch(:reaction, {})
    end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_form.html.erb
<%= form_with(model: reaction, local: true) do |form| %>
  <% if reaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>

      <ul>
        <% reaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reactions/edit.html.erb
<h1>Editing Reaction</h1>

<%= render 'form', reaction: @reaction %>

<%= link_to 'Show', @reaction %> |
<%= link_to 'Back', reactions_path %>

app/views/reactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reactions.each do |reaction| %>
      <tr>
        <td><%= link_to 'Show', reaction %></td>
        <td><%= link_to 'Edit', edit_reaction_path(reaction) %></td>
        <td><%= link_to 'Destroy', reaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reaction', new_reaction_path %>

app/views/reactions/new.html.erb
<h1>New Reaction</h1>

<%= render 'form', reaction: @reaction %>

<%= link_to 'Back', reactions_path %>

app/views/reactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reaction_path(@reaction) %> |
<%= link_to 'Back', reactions_path %>