config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  scope controller: :static_pages do
    get '/help' => :help
    get '/about' => :about
    get '/contact' => redirect("https://github.com/alexsmartens")
  end

  get '/signup', :to => 'users#new'

  scope controller: :sessions do
    get '/login' => :new
    post '/login' => :create
    delete '/logout' => :destroy
  end

  # "resources :resource" - automatically generate a full suite of RESTful routes
  resources :users do
    # "member" method adds additional routes to respond to URLs containing
    # the user id, eg. "/users/id/following" and "/users/id/followers"
    member do
      get :following, :followers
    end
    # "collection" method adds additional routes to respond to URLs without the
    # id, eg. "/users/tigers" as in the method below
    #     collection do
    #       get :tigers
    #     end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reactions

  # Custom handling of common errors
   match "/404", to: "errors#not_found", via: :all
   match "/500", to: "errors#internal_server_error", via: :all
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if get_current_user.microposts.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%# params: {controller: :static_pages, action: :home} fixes a micropost
      indexing/pagination problem after an invalid micropost post call is issued
  %>
  <%= will_paginate @feed_items, params: {controller: :static_pages, action: :home} %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%# 1. When constructing a form using form_with(@user), Rails uses POST
        if @user.new_record? is true and PATCH if it is false. %>
  <%# 2. Since web browsers can’t natively send PATCH requests Rails fakes
        it with a POST request and a HIDDEN INPUT field (this field can be
        checked when the form is rendered with a web inspector) %>

  <%# f.object is an object associated with the form %>
  <%= render "shared/error_messages", object: f.object %>
  <div>
    <%# the id of the below field is "micropost_content" and the name
        is "micropost[content]""
    %>
    <%= f.text_area :content, placeholder: "Compose new post...", required: "required" %>
  </div>
  <span class="image">
    <%# (1) the id of the below field is "micropost_image" and the name
          is "micropost[image]""
        (2) 'accept: "image/jpeg,image/gif,image/png"' allows only valid images
          to be selected by graying out any other file types
    %>
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<%# Limit max image size to 5 megabytes %>
<script type="text/javascript">
  $("#micropost_image").bind("change", function() {
    const size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.")
      $("#micropost_image").val("")
    }
  })
</script>

app/views/shared/_stats.html.erb
<% @user ||= get_current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(get_current_user, size: 50), get_current_user %>
<h1><%= get_current_user.name %></h1>
<span><%= link_to "view my profile", get_current_user %></span>
<span><%= pluralize(get_current_user.microposts.count, "micropost") %></span>