config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  scope controller: :static_pages do
    get '/help' => :help
    get '/about' => :about
    get '/contact' => redirect("https://github.com/alexsmartens")
  end

  get '/signup', :to => 'users#new'

  scope controller: :sessions do
    get '/login' => :new
    post '/login' => :create
    delete '/logout' => :destroy
  end

  # "resources :resource" - automatically generate a full suite of RESTful routes
  resources :users do
    # "member" method adds additional routes to respond to URLs containing
    # the user id, eg. "/users/id/following" and "/users/id/followers"
    member do
      get :following, :followers
    end
    # "collection" method adds additional routes to respond to URLs without the
    # id, eg. "/users/tigers" as in the method below
    #     collection do
    #       get :tigers
    #     end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reactions

  # Custom handling of common errors
   match "/404", to: "errors#not_found", via: :all
   match "/500", to: "errors#internal_server_error", via: :all
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        © 2020 Alex Martens. All rights reserved.
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><a href="https://github.com/alexsmartens">Contact </a>
            </li>
        </ul>
    </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to image_tag("logo.svg", alt: "Twitter By Alex logo", height: "30"), root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
          id="bs-example-navbar-collapse-1">
        <li> <%= link_to  "Home", root_path %> </li>
        <li> <%= link_to  "Help", help_path %> </li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <%# [About the below line] @current_user can be potentially used
              instead of get_current_user because it should be always available
              after the logged_in? call  above %>
              <%# <li><%= link_to "Profile", @current_user  ></li> %>
              <li><%= link_to "Profile", get_current_user %></li>
              <li><%= link_to "Settings", edit_user_path(get_current_user) %></li>
              <li class="divider"></li>
              <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<%# HTML5 shim, to be accessible only by older browsers, specifically Internet Explorer of the version less then 9 %>
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js" </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <%= render "layouts/head" %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}")%>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <script>
      /* Control sidebar and content-container on window load */
      $(document).ready(function() {
        // BUG (potential): page is loaded multiple times which causes flickering

        /* Show and resize sidebar on window load */
        // let $affixElement = $('aside[data-spy="affix"]');
        let $sidebar = $("#sidebar");
        resize_width_to_parent($sidebar);
        $sidebar.css("visibility", "visible");

        /* Imitate content if there is not enough in the container */
        if ($sidebar.parent().parent().height() <= 350) {
          $("#content-container").css("height", 350);
          // BUG (potential): sidebar jumps down on refresh, the below line
          // is a temporary fix
          $sidebar.css("top", $sidebar.parent().parent().offset().top);
        }
      });

      /* Resize sidebar on page resize */
      $(window).on("resize", function(){
        let $sidebar = $("#sidebar");
        resize_width_to_parent($sidebar);
      });

      /* Make the passed element width equal to the parent width */
      function resize_width_to_parent($element) {
        $element.width($element.parent().width());
      }
    </script>

  </body>
</html>